# br_patchworkpp config

# Map information
resolution: 0.3
num_class: 4 # Number of classes

# Sampling resolutions
free_resolution: 100 # Free space sampling resolution
ds_resolution: 0.1 # Downsampling factor

# Information about range-finder data
max_range: -1 # Sensor max range (m)